### PR TITLE
32 change to ngx admin template

### PR DESCRIPTION
**Pull request by giobart**
I reset the branch and re-opened this PR for the following reasons:

- Service deployment issue: deploying one service triggers, for some reason, 2 or 3 concurrent deployments.  
- Service status (green, red) dots disappeared
- Service deployment form is not pre-filled and requires manual adjusting of the memory and cpu values. We can use default 100MB, 1 cpu values.

### CODE REVIEW

**Review by danimair9 — APPROVED** [review]

**Comment by giobart** [comment]
@danimair9 regarding these problems:
- Service deployment issue: deploying one service triggers, for some reason, 2 or 3 concurrent deployments.
- Service status (green, red) dots disappeared
- Service deployment form is not pre-filled and requires manual adjusting of the memory and cpu values. We can use default 100MB, 1 cpu values.

Should I open up different issues? What do you think?

**Comment by danimair9** [comment]
Yes, I think we should create new issues for it and merge this PR as soon as we can so that others can also continue to work with this version. Because currently we have the problem that people create new PRs for the old version and we would need to adjust these changes to the new version as well.

Also, the individual bugs should be solved pretty quickly, which then I or another person who would like to get into Oakestra can do.

**Comment by giobart** [comment]
## Just pushed the following fixes:

### App Status
image
App statuses color-encoded are back!

### Spinners
Screenshot 2023-12-21 at 12 47 27
Now the deployment spinners are showing as well with the new template

### Logs 
Screenshot 2023-12-21 at 12 48 48
Included application logs within the new interface 

### Double deployments
With the new template and redux, we had the issue that by clicking the deploy button, sometimes the applications got deployed several times. This is now fixed.

### Deploy all button
This button is now triggering the refresh of redux, and therefore, the page will update.

**Review by nitindermohan — APPROVED** [review]
Approved!

**Pull request merged**
